### ISSUE TITLE
mn2pdf processing hang with 1060-M.1400/T-SP-M.1400-2014-E

### ISSUE THREAD

**Issue by ronaldtse** [ituob/service-publications-docs#34]
`1060-M.1400/T-SP-M.1400-2014-E.adoc` hangs in PDF generation.

```sh
$ cd sources/1060-M.1400
$ bundle exec metanorma T-SP-M.1400-2014-E.adoc
[info]: Compiling /Users/me/src/ituob/service-publications-docs/1060-M.1400/T-SP-M.1400-2014-E.adoc ...
Metanorma XML Style Warning: (XML Line 000074): Table should have title
Metanorma XML Style Warning: (XML Line 018958): Table should have title
Metanorma XML Style Warning: (XML Line 018980): Table should have title
Style: No Summary has been provided
Style: No Keywords have been provided
Local cache version is obsolete.
Style: Annex to ITU OB E.212 does not match ITU document identifier conventions
Document Attributes: published is not a recognised status
Metanorma XML Syntax: (XML Line 018939:73): element "fn" not allowed here; expected the element end-tag, text or element "add", "bookmark", "br", "concept", "del", "em", "eref", "erefstack", "hr", "image", "index", "index-xref", "keyword", "link", "pagebreak", "ruby", "smallcap", "span", "stem", "strike", "strong", "sub", "sup", "svg", "tt", "underline" or "xref"
Metanorma XML Syntax: (XML Line 019028:16): element "itu-standard" incomplete; missing required element "bibliography"
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/mn2pdf-1.62/lib/../bin/mn2pdf.jar --xml-file "/Users/me/src/ituob/service-publications-docs/_site/documents/1060-M.1400/T-SP-M.1400-2014-E.presentation.xml" --xsl-file "/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-itu-2.2.6/lib/isodoc/itu/itu.service-publication.xsl" --pdf-file "/Users/me/src/ituob/service-publications-docs/_site/documents/1060-M.1400/T-SP-M.1400-2014-E.pdf" --param baseassetpath="/Users/me/src/ituob/service-publications-docs/1060-M.1400" --syntax-highlight  --font-manifest "/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20230309-8344-zk830u.yml"
```

**Comment by ronaldtse** [comment]
These are also hanging:

```
      # - 1109-Q.708B/T-SP-Q.708B-2016-E.adoc
      # - 1109-Q.708B/T-SP-Q.708B-2016-F.adoc
      # - 1109-Q.708B/T-SP-Q.708B-2016-S.adoc
```

**Comment by Intelligent2013** [comment]
`bundle exec metanorma T-SP-Q.708B-2016-E.adoc`:
```
[INFO] Generation of XSL-FO with information about the table's widths ...
PDFGenerator.applyXSLT[tables_only.xsl] processing time: 1415 milliseconds
Exception in thread "main" java.lang.StackOverflowError
        at org.apache.xml.utils.NodeVector.clone(NodeVector.java:89)
        at org.apache.xpath.NodeSetDTM.clone(NodeSetDTM.java:255)
        at org.apache.xml.dtm.ref.DTMNodeIterator.<init>(DTMNodeIterator.java:74)
```

**Comment by Intelligent2013** [comment]
The `StackOverflowError` occurs due the recursive calls the template
```xml
<xsl:template match="tr" mode="simple-table-rowspan">
...
	<xsl:apply-templates select="following-sibling::tr[1]" mode="simple-table-rowspan">
		<xsl:with-param name="previousRow" select="$newRow"/>
	</xsl:apply-templates>
</xsl:template>
```

The table contains >6000 rows, but the error occurs on 930 lines.
Will try optimize.

**Comment by ronaldtse** [comment]
@Intelligent2013 can I confirm these documents now run properly? Thanks.

**Comment by Intelligent2013** [comment]
Performance testing for these documents:
```
      - 1060-M.1400/T-SP-M.1400-2014-A.adoc
      - 1060-M.1400/T-SP-M.1400-2014-C.adoc
      - 1060-M.1400/T-SP-M.1400-2014-E.adoc
      - 1060-M.1400/T-SP-M.1400-2014-F.adoc
      - 1060-M.1400/T-SP-M.1400-2014-R.adoc
      - 1060-M.1400/T-SP-M.1400-2014-S.adoc
      - 1109-Q.708B/T-SP-Q.708B-2016-E.adoc
      - 1109-Q.708B/T-SP-Q.708B-2016-F.adoc
      - 1109-Q.708B/T-SP-Q.708B-2016-S.adoc
```
https://github.com/ituob/service-publications-docs/actions/runs/4498740621/jobs/7915731565?pr=39

**Comment by Intelligent2013** [comment]
36 min and still processing:
```
[info]: Compiling /Users/runner/work/service-publications-docs/service-publications-docs/1060-M.1400/T-SP-M.1400-2014-C.adoc ...
Anchors: (XML Line 000015): normalised identifier in <clause id="___x7535___x4fe1___x6807___x51c6___x5316___x5c40___x8bf4___x660e_" inline-header="false" obligation="informative"/> from _电信标准化局说明
Anchors: (XML Line 018914): normalised identifier in <clause id="___x56fd___x9645___x7535___x8054___x7535___x4fe1___x8fd0___x8425___x5546___x4ee3___x7801___x5217___x8868___x901a___x77e5___x8868___x683c_" inline-header="false" obligation="normative"/> from _国际电联电信运营商代码列表通知表格
Anchors: (XML Line 018957): normalised identifier in <clause id="___x4fee___x6539_" inline-header="false" obligation="normative"/> from _修改
Metanorma XML Style Warning: (XML Line 000057): Table should have title
Metanorma XML Style Warning: (XML Line 018938): Table should have title
Metanorma XML Style Warning: (XML Line 018959): Table should have title
Style: No Summary has been provided
Style: No Keywords have been provided
Style: 国际电联操作公报附件 第 M.1400 期 does not match ITU document identifier conventions
Document Attributes: published is not a recognised status
Metanorma XML Syntax: (XML Line 018922:43): element "fn" not allowed here; expected the element end-tag, text or element "add", "bookmark", "br", "concept", "del", "em", "eref", "erefstack", "hr", "image", "index", "index-xref", "keyword", "link", "pagebreak", "ruby", "smallcap", "span", "stem", "strike", "strong", "sub", "sup", "svg", "tt", "underline" or "xref"
Metanorma XML Syntax: (XML Line 019007:16): element "itu-standard" incomplete; missing required element "bibliography"
java -Xss5m -Xmx2048m -Djava.awt.headless=true -Dapple.awt.UIElement=true -jar /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/packed-mn-20230323-13612-4vpyo1/mn2pdf.jar --xml-file "/Users/runner/work/service-publications-docs/service-publications-docs/_site/documents/1060-M.1400/T-SP-M.1400-2014-C.presentation.xml" --xsl-file "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/packed-mn-20230323-13612-4vpyo1/itu.service-publication.xsl" --pdf-file "/Users/runner/work/service-publications-docs/service-publications-docs/_site/documents/1060-M.1400/T-SP-M.1400-2014-C.pdf" --param baseassetpath="/Users/runner/work/service-publications-docs/service-publications-docs/1060-M.1400" --syntax-highlight  --font-manifest "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/fontist_locations20230323-13612-oaqokx.yml"
```

Cancelled.

**Comment by Intelligent2013** [comment]
### Test 1 (locally on Win).
`metanorma.yml`:
```
---
metanorma:
  source:
    files:
      - 1060-M.1400/T-SP-M.1400-2014-E.adoc

  collection:
    organization: "ITU"
    name: "ITU Operational Bulletin Documents"
```

Run `bundle exec metanorma site generate --agree-to-terms`:

```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
[info]: Compiling D:/Work/Metanorma/repositories/service-publications-docs.copy4/1060-M.1400/T-SP-M.1400-2014-E.adoc ...
Metanorma XML Style Warning: (XML Line 000072): Table should have title
Metanorma XML Style Warning: (XML Line 018956): Table should have title
Metanorma XML Style Warning: (XML Line 018978): Table should have title
Style: No Summary has been provided
Style: No Keywords have been provided
Style: Annex to ITU OB E.212 does not match ITU document identifier conventions
Document Attributes: published is not a recognised status
Metanorma XML Syntax: (XML Line 018937:73): element "fn" not allowed here; expected the element end-tag, text or element "add", "bookmark", "br", "concept", "del", "em", "eref", "erefstack", "hr", "image", "index", "index-xref", "keyword", "link", "pagebreak", "ruby", "smallcap", "span", "stem", "strike", "strong", "sub", "sup", "svg", "tt", "underline" or "xref"
Metanorma XML Syntax: (XML Line 019026:16): element "itu-standard" incomplete; missing required element "bibliography"
java -Xss5m -Xmx2048m -Djava.awt.headless=true -Duser.home=C:/Users/TestUser -jar C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/mn2pdf-1.65.1/lib/../bin/mn2pdf.jar --xml-file "D:/Work/Metanorma/repositories/service-publications-docs.copy4/_site/documents/1060-M.1400/T-SP-M.1400-2014-E.presentation.xml" --xsl-file "C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-itu-2.2.7/lib/isodoc/itu/itu.service-publication.xsl" --pdf-file "D:/Work/Metanorma/repositories/service-publications-docs.copy4/_site/documents/1060-M.1400/T-SP-M.1400-2014-E.pdf" --param baseassetpath="D:/Work/Metanorma/repositories/service-publications-docs.copy4/1060-M.1400" --syntax-highlight  --font-manifest "C:/Users/TestUser/AppData/Local/Temp/fontist_locations20230323-7772-vzu689.yml"
```
after 3 min the PDF generated, but ruby is still working.
In the process list:
- after PDF generation no `java` in the process list
- `ruby` process takes 25% (one CPU core) and 673Mb memory.

**Comment by Intelligent2013** [comment]
### Test 2 (locally on WIn)
```
cd 1060-M.1400 
bundle exec metanorma -t itu -x pdf T-SP-M.1400-2014-E.adoc 
```
```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Metanorma XML Style Warning: (XML Line 000072): Table should have title
Metanorma XML Style Warning: (XML Line 018956): Table should have title
Metanorma XML Style Warning: (XML Line 018978): Table should have title
Style: No Summary has been provided
Style: No Keywords have been provided
Style: Annex to ITU OB E.212 does not match ITU document identifier conventions
Document Attributes: published is not a recognised status
Metanorma XML Syntax: (XML Line 018937:73): element "fn" not allowed here; expected the element end-tag, text or element "add", "bookmark", "br", "concept", "del", "em", "eref", "erefstack", "hr", "image", "index", "index-xref", "keyword", "link", "pagebreak", "ruby", "smallcap", "span", "stem", "strike", "strong", "sub", "sup", "svg", "tt", "underline" or "xref"
Metanorma XML Syntax: (XML Line 019026:16): element "itu-standard" incomplete; missing required element "bibliography"
java -Xss5m -Xmx2048m -Djava.awt.headless=true -Duser.home=C:/Users/TestUser -jar C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/mn2pdf-1.65.1/lib/../bin/mn2pdf.jar --xml-file "D:/Work/Metanorma/repositories/service-publications-docs.copy4/1060-M.1400/T-SP-M.1400-2014-E.presentation.xml" --xsl-file "C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-itu-2.2.7/lib/isodoc/itu/itu.service-publication.xsl" --pdf-file "D:/Work/Metanorma/repositories/service-publications-docs.copy4/1060-M.1400/T-SP-M.1400-2014-E.pdf" --syntax-highlight  --font-manifest "C:/Users/TestUser/AppData/Local/Temp/fontist_locations20230323-6508-pz5t8r.yml"
```

after 3 min the PDF generated, and the process stops.

**Comment by ronaldtse** [comment]
On my macOS:

```sh
$ time bundle exec metanorma T-SP-M.1400-2014-E.adoc
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Metanorma XML Style Warning: (XML Line 000072): Table should have title
Metanorma XML Style Warning: (XML Line 018956): Table should have title
Metanorma XML Style Warning: (XML Line 018978): Table should have title
Style: No Summary has been provided
Style: No Keywords have been provided
Style: Annex to ITU OB E.212 does not match ITU document identifier conventions
Document Attributes: published is not a recognised status
Metanorma XML Syntax: (XML Line 018937:73): element "fn" not allowed here; expected the element end-tag, text or element "add", "bookmark", "br", "concept", "del", "em", "eref", "erefstack", "hr", "image", "index", "index-xref", "keyword", "link", "pagebreak", "ruby", "smallcap", "span", "stem", "strike", "strong", "sub", "sup", "svg", "tt", "underline" or "xref"
Metanorma XML Syntax: (XML Line 019026:16): element "itu-standard" incomplete; missing required element "bibliography"
java -Xss5m -Xmx2048m -Djava.awt.headless=true -Dapple.awt.UIElement=true -Duser.home=/Users/mulgogi -jar ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/mn2pdf-1.66/lib/../bin/mn2pdf.jar --xml-file "~/src/ituob/service-publications-docs/1060-M.1400/T-SP-M.1400-2014-E.presentation.xml" --xsl-file "~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-itu-2.2.7/lib/isodoc/itu/itu.service-publication.xsl" --pdf-file "~/src/ituob/service-publications-docs/1060-M.1400/T-SP-M.1400-2014-E.pdf" --syntax-highlight  --font-manifest "/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20230324-3478-ieasso.yml"

real	6m56.464s
user	7m50.211s
sys	0m22.623s
```

The `T-SP-M.1400-2014-E.adoc` file does complete.

**Comment by ronaldtse** [comment]
I have tested the following documents with the site generate command too and it does work.

## T-SP-M.1400-2014-E

```sh
$ time bundle exec metanorma site generate
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
[info]: Compiling ~/src/ituob/service-publications-docs/1060-M.1400/T-SP-M.1400-2014-E.adoc ...
Metanorma XML Style Warning: (XML Line 000072): Table should have title
Metanorma XML Style Warning: (XML Line 018956): Table should have title
Metanorma XML Style Warning: (XML Line 018978): Table should have title
Style: No Summary has been provided
Style: No Keywords have been provided
Local cache version is obsolete.
Style: Annex to ITU OB E.212 does not match ITU document identifier conventions
Document Attributes: published is not a recognised status
Metanorma XML Syntax: (XML Line 018937:73): element "fn" not allowed here; expected the element end-tag, text or element "add", "bookmark", "br", "concept", "del", "em", "eref", "erefstack", "hr", "image", "index", "index-xref", "keyword", "link", "pagebreak", "ruby", "smallcap", "span", "stem", "strike", "strong", "sub", "sup", "svg", "tt", "underline" or "xref"
Metanorma XML Syntax: (XML Line 019026:16): element "itu-standard" incomplete; missing required element "bibliography"
java -Xss5m -Xmx2048m -Djava.awt.headless=true -Dapple.awt.UIElement=true -Duser.home=/Users/mulgogi -jar ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/mn2pdf-1.66/lib/../bin/mn2pdf.jar --xml-file "~/src/ituob/service-publications-docs/_site/documents/1060-M.1400/T-SP-M.1400-2014-E.presentation.xml" --xsl-file "~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-itu-2.2.7/lib/isodoc/itu/itu.service-publication.xsl" --pdf-file "~/src/ituob/service-publications-docs/_site/documents/1060-M.1400/T-SP-M.1400-2014-E.pdf" --param baseassetpath="~/src/ituob/service-publications-docs/1060-M.1400" --syntax-highlight  --font-manifest "/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20230324-14097-o5u9z2.yml"
[info]: Building collection file: ~/src/ituob/service-publications-docs/_site/documents.xml ...
[relaton-bib] WARNING: invalid relation type: complements
[relaton-bib] WARNING: invalid relation type: complements
[relaton-bib] WARNING: invalid relation type: complements
[info]: Generating html site in ~/src/ituob/service-publications-docs/_site ...
[relaton-bib] WARNING: invalid relation type: complements
[relaton-bib] WARNING: invalid relation type: complements
[relaton-bib] WARNING: invalid relation type: complements
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Site has been generated at ~/src/ituob/service-publications-docs/_site

real	6m56.547s
user	7m51.170s
sys	0m22.491s
```

**Comment by ronaldtse** [comment]
What doesn't work is:
```sh
$ time bundle exec metanorma 1109-Q.708B/T-SP-Q.708B-2016-E.adoc
```

As pointed out by @Intelligent2013 , the Java portion completes but the Ruby portion never completes. The PDF file is actually generated too.

Will file this as a new issue.
